[book]
authors = ["ThatGuyJamal"]
language = "en"
multilingual = true
src = "src"
title = "JavaScript For Programmers by ThatGuyJamal"

# Build configuration
[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

#  Base HTML configuration
[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/ThatGuyJamal/js-book"
edit-url-template = "https://github.com/ThatGuyJamal/js-book/docs/{path}"
default-theme = "Ayu"

# Book search configuration (Disabled)
 [output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

# MD-book linkcheck configuration
[output.linkcheck]
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = false
# Are we allowed to link to files outside of the book's root directory? This
# may help prevent linking to sensitive files (e.g. "../../../../etc/shadow")
traverse-parent-directories = false
# If necessary, you can exclude one or more links from being checked with a
# list of regular expressions. The regex will be applied to the link href (i.e.
# the `./index.html` in `[some page](./index.html)`) so it can be used to
# ignore both web and filesystem links.
exclude = [ 'google\.com' ]
# The User-Agent to use when sending web requests
user-agent = "mdbook-linkcheck-0.4.0"
# The number of seconds a cached result is valid for (12 hrs by default)
cache-timeout = 43200
# How should warnings be treated?
# - "warn" will emit warning messages
# - "error" treats all warnings as errors, failing the linkcheck
# - "ignore" will ignore warnings, suppressing diagnostic messages and allowing
warning-policy = "warn"
# Extra HTTP headers that must be send to certain web sites
# in order to link check to succeed.
# This is a dictionary (map), with keys being regexes
# matching a set of web sites, and values being an array of
# the headers.
[output.linkcheck.http-headers]
# Any hyperlink that contains this regexp will be sent
# the "Accept: text/html" header
'crates\.io' = ["Accept: text/html"]